name: Build Binaries

on:
  push:
    branches:
      - master # creates a pre-release
  release:
    types:
      - released # does not include pre-release

jobs:
  build-binaries:
    name: cicd
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
            GOOS: "linux"
          - GOARCH: "386"
            GOOS: "linux"
          - GOARCH: "arm64"
            GOOS: "linux"
          - GOARCH: "amd64"
            GOOS: "darwin"
          - GOARCH: "arm64"
            GOOS: "darwin"
          - GOARCH: "amd64"
            GOOS: "windows"
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@master
      - name: Cache Go Build and Modules
        id: cache-go-modules
        uses: actions/cache@v2
        with:
          path: |
            .cache-modules
            .cache-go-build
          key: ${{ runner.os }}-golang-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('golang/go.sum') }}-v1
          restore-keys: |
            ${{ runner.os }}-golang-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-
      - name: Get Dependencies
        if: steps.cache-go-modules.outputs.cache-hit != 'true'
        uses: unfor19/release-action/golang/1.16@master
        with:
          lang-name: golang
          lang-version: 1.16
          action: dependencies
      - name: Go Build
        uses: unfor19/release-action/golang/1.16@master
        with:
          lang-name: golang
          lang-version: 1.16
          action: build
      # - name: Go Test
      #   uses: unfor19/release-action/golang/1.16@master
      #   with:
      #     lang-name: golang
      #     lang-version: 1.16
      #     action: test
      - name: Release
        uses: unfor19/release-action/golang/1.16@master
        with:
          lang-name: golang
          lang-version: 1.16
          action: release
          gh-token: ${{ secrets.GH_TOKEN }}
