name: Release Binaries

on:
  release:
    types: [published] # does not include pre-release
  push:
    branches: [master] # creates a pre-release

jobs:
  release-linux-binaries:
    name: linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
          - GOARCH: "386"
          - GOARCH: "arm64"
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: unfor19/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GOARCH: ${{ matrix.GOARCH }}
          GOOS: linux

  release-macos-binaries:
    name: macos-darwin
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
          - GOARCH: "arm64"
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: unfor19/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GOARCH: ${{ matrix.GOARCH }}
          GOOS: darwin

  release-windows-binaries:
    name: windows
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
          - GOARCH: "386"
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: unfor19/go-release.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GOARCH: ${{ matrix.GOARCH }}
          GOOS: windows
